add_newline = false
format = """$all$character"""

[line_break]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

# # Custom remote indicator module
# [custom.remote_indicator]
# # Check if SSH_CONNECTION environment variable is set
# when = "test -n \"$SSH_CONNECTION\""
# # The format uses a small globe icon and a light style
# format = "[üåç](dimmed green) "
# # You can change the symbol to something even smaller, like a simple letter R
# # format = "[R](bold red) "
# # Run the check quickly
# command = ""
